# Generated by Django 5.0.6 on 2024-06-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salar',
            new_name='Seller',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('client', 'client'), ('seller', 'seller'), ('admin', 'admin')], default='client', max_length=100),
        ),
    ]
